apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
nodeRegistration:
  kubeletExtraArgs:
    enable-controller-attach-detach: "false"
    node-labels: "node-type=rook"
discovery:
  bootstrapToken:
    apiServerEndpoint: kubedev.dev.local
    token: bc989v.8vmj4cxbumc9d7q7
    caCertHashes:
    - sha256:97e29f484791b1d9720d432eb9d24b61170aeac7036713b74e512f52e1b108dc
