apiVersion: kubeadm.k8s.io/v1beta1
kind: JoinConfiguration
nodeRegistration:
kubeletExtraArgs:
enable-controller-attach-detach: "false"
node-labels: "node-type=rook"
discovery:
bootstrapToken:
apiServerEndpoint: ${KUBEADM_API_ENDPOINT_INTERNAL}
 token: ${KUBEADM_TOKEN}
 caCertHashes:
 - ${CA_CERT_HASH}
