apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: pihole01-frontend-ip
  namespace: metallb-system
spec:
  addresses:
  - 10.0.69.41/32
  autoAssign: true
---
#apiVersion: storage.k8s.io/v1
#kind: StorageClass
#metadata:
#  name: pihole
#provisioner: driver.longhorn.io
#allowVolumeExpansion: true
#parameters:
#  numberOfReplicas: "3"
#  staleReplicaTimeout: "2880" # 48 hours in minutes
#  fromBackup: ""
#  fsType: "ext4"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole01-etc-pihole-pvc
  namespace: pihole01
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: pihole01-etc-dnsmasq.d-pvc
#  namespace: pihole01
#spec:
#  accessModes:
#    - ReadWriteOnce
#  storageClassName: longhorn
#  volumeMode: Filesystem
#  resources:
#    requests:
#      storage: 2Gi
---
