apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole01-etc-pihole-pvc
  namespace: pihole-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  hostPath: "/etc/pihole"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole01-etc-dnsmasq.d-pvc
  namespace: pihole-system
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi
  hostPath: "/etc/dnsmasq.d"
---
