#!/bin/bash
# Argument validation check
if [ "$#" -ne 3 ]; then
	echo "Usage: $0 <chart_name> <chart_repo_name> <chart_repo_url>"
	exit 1
fi
# Variables
# Replace with your desired chart respository and chart name
export HELM_DIR="/opt/helm"
export CHART_REPO_NAME=${2}
export CHART_REPO_URL=${3}
export CHART_NAME=${1}
export CHART_DIR="${HELM_DIR}/${CHART_NAME}"
echo
echo --------------------
echo
echo Create Helm directory if not exist
mkdir -p "${HELM_DIR}"
echo
echo --------------------
echo
echo Add ${CHART_REPO_URL} to Helm
helm repo add ${CHART_REPO_NAME} ${CHART_REPO_URL}
helm repo update
echo
echo --------------------
echo
echo Download the chart
echo Chart Repo: "${CHART_REPO_NAME}"
echo Chart Name: "${CHART_NAME}"
echo
helm pull "${CHART_REPO_NAME}/${CHART_NAME}" --untar --untardir "${CHART_DIR}"
echo
echo --------------------
echo
echo Navigate to the downloaded chart directory
cd ${CHART_DIR}
echo
echo Chart Dir: "${CHART_NAME}"
echo
echo --------------------
echo
echo Update dependencies to download required packages locally
helm dependency update
echo
echo --------------------
echo
echo Identify all image names from the chart
echo
# Search for all images from the values.yaml files that were contained in the Helm chart
find ${CHART_DIR} -name "values.yaml" -type f -exec egrep -oh "image: (.+)" {} \; | awk '{print $2}' > ${CHART_DIR}/images.txt

IMAGE_NAMES=$(grep -Eo "image: ([^:]+)" values.yaml | awk '{print $2}')
echo
echo Chart Images
cat ${CHART_DIR}/images.txt
echo
echo "${IMAGE_NAMES}"
echo
echo --------------------
echo
echo Pull images for offline installation
#for image in ${IMAGE_NAMES}; do
#	echo "${image}"; sudo nerdctl pull "${image}"
#done
echo
echo Image: "{$image}"
echo
echo --------------------
echo
echo Tag images for offline-registry.dev.local
#for image in ${IMAGE_NAMES}; do
#	sudo nerdctl tag "${image}" "kuberegistry.dev.local/${image}"
#done
echo
echo --------------------
echo Push images to offline-registry.dev.local
#for image in ${IMAGE_NAMES}; do
#	sudo nerdctl push "kuberegistry.dev.local/${image}"
#done
echo
echo --------------------
echo
echo Package chart for offline distribution
helm package . -d ${HELM_DIR}/packages
echo
echo --------------------
echo
echo Done
echo "Helm chart '${CHART_NAME}' and its dependencies downloaded successfully!"
echo
echo

