apiVersion: kubeadm.k8s.io/v1beta4
bootstrapTokens:
- groups:
  - system:bootstrappers:kubeadm:default-node-token
  token: "${KUBEADM_TOKEN}"
  ttl: 24h0m0s
  usages:
  - signing
  - authentication
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: ${KUBEADM_API_ADVERTISE_IP_1}
  bindPort: 6443
---
apiServer:
  certSANs:
  - ${KUBEADM_API_ENDPOINT_INTERNAL}
  - ${KUBEADM_API_ENDPOINT}
  extraArgs:
    max-requests-inflight: "1000"
    max-mutating-requests-inflight: "500"
    default-watch-cache-size: "500"
    watch-cache-sizes: "persistentvolumeclaims#1000,persistentvolumes#1000"
apiVersion: kubeadm.k8s.io/v1beta4
certificatesDir: ${KUBEADM_PKI_HOMEDIR}
clusterName: ${KUBEADM_CLUSTER_NAME}
controlPlaneEndpoint: ${KUBEADM_API_ENDPOINT_INTERNAL}:6443
controllerManager:
  extraArgs:
    deployment-controller-sync-period: "50s"
encryptionAlgorithm: RSA-2048
etcd:
  local:
    dataDir: /var/lib/etcd
imageRepository: registry.k8s.io
kind: ClusterConfiguration
kubernetesVersion: ${KUBEADM_K8S_VERSION}
networking:
  dnsDomain: ${KUBEADM_DNS_DOMAIN}
  serviceSubnet: ${KUBEADM_SERVICE_SUBNET}
  podSubnet: ${KUBEADM_POD_SUBNET}