apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole-pods
  namespace: dns-pihole
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-clusterip
  namespace: dns-pihole
spec:
  selector:
    app: pihole
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 80
  type: ClusterIP